services:
  vue_template:
    container_name: vue_tmplt
    image: vue_tmplt
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./vue_folder:/vue_folder
      
    ports:
      - "5071:5071"
